### ISSUE TITLE
Hello! (regarding fuzzyrusty)

### ISSUE THREAD

**Issue by logannc** [JacksonGariety/dotfiles#1]
I apologize for polluting your issue-space, but I didn't know how else to contact you!

You own the crate `fuzzyrusty` on crates.io which seems to just be my dinky little library logannc/fuzzyrusty. There is a little bit of activity going on there, getting ever closer to feature parity with fuzzywuzzy. I was hoping to update the crate when this work was done but realized I don't own the crate!

I tried to get your information via crates.io but they told me you didn't have an email associated with your account.

Please reach out to me via email (logan.neal.collins@gmail.com) to discuss next steps. Thanks!

**Comment by ColemanGariety** [comment]
I sent you an email
